spring:
  mvc:
    view:
      suffix: .html
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # ?? ??? ?? Entity Class ???? Table ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cookie?serverTimezone=Asia/Seoul
    username: root
    password: 11111111
    secretKey: hjw
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    root: info
    com.zaxxer.hikari.HikariConfig: debug
    org.hibernate.SQL: debug
    hibernate.type.descriptor.sql.BasicBinder: trace