spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cookie?serverTimezone=Asia/Seoul
    username: cookie
    password: gdsc2cookie
    secretKey: hjw

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        user_sql_cooments: true

    hibernate:
      ddl-auto: create

