spring:
  mvc:
    view:
      suffix: .html
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # ?? ??? ?? Entity Class ???? Table ??
  datasource:
    url: jdbc:mysql://localhost:3306/cookieparking?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true # ?? ??? ?? schema ? ?? ?? ??
    username: root
    password: 74147414l
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    root: info
    com.zaxxer.hikari.HikariConfig: debug
    org.hibernate.SQL: debug
    hibernate.type.descriptor.sql.BasicBinder: trace